export const ROUTES_MAP = {
  MAIN: 'main',
  ABOUT_ME: 'about-me',
  PROJECTS: 'projects',
  CONTACT_ME: 'contact-me',
  PROFESSIONAL_INFO: 'professional-info',
  PROFESSIONAL_INFO_SKILLS: 'professional-info-skills',
  PROFESSIONAL_INFO_EXPERIENCE: 'professional-info-experience',
  PROFESSIONAL_INFO_COURSES: 'professional-info-courses',
  PROFESSIONAL_INFO_UNIVERSITY: 'professional-info-university',
  PERSONAL_INFO: 'personal-info',
  PERSONAL_INFO_BIO: 'personal-info-bio',
  PERSONAL_INFO_INTERESTS: 'personal-info-interests',
  HOBBIES: 'hobbies',
  HOBBIES_BOOKS: 'hobbies-books',
  HOBBIES_GAMES: 'hobbies-games',
  HOBBIES_MUSIC: 'hobbies-music',
} as const;
